#!/bin/bash

sudo dhclient eth1
rm -rf networks5
git clone https://github.com/semiondu/networks5.git
cp networks5/tcp-cubic-test.py ../mininet/mininet/examples
cp networks5/restart .

cd mininet/mininet/examples
